version: "3.3"

services:
  backend:
    container_name: backend
    build: .
    networks:
      - stack
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - media:/media/
    env_file:
      - .env
    command: /bin/bash -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: postgres:15-alpine
    networks:
      - stack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

networks:
  stack:

volumes:
  postgres_data:
  media:
  static: