# Generated by Django 4.2.7 on 2023-11-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_files', models.FileField(blank=True, null=True, upload_to='upload_files', verbose_name='Загрузка')),
            ],
            options={
                'verbose_name': 'Excel файлы',
                'verbose_name_plural': 'Excel файлы',
            },
        ),
    ]
